[project]
name = "convolution"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "numpy>=2.4.1",
    "scipy>=1.17.0",
    "soundfile>=0.13.1",
]
